apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: company-a-namespace
type: Opaque
data:
  username: YWRtaW4=
  password: Y2xvdWRzeXN0ZW0=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: company-b-namespace
type: Opaque
data:
  username: YWRtaW4=
  password: Y2xvdWRzeXN0ZW0=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: db-namespace
type: Opaque
data:
  username: YWRtaW4=
  password: Y2xvdWRzeXN0ZW0=
